#!/usr/bin/env python3
"""
Build .env.local from .streamlit/secrets.toml so the Next.js app can run locally
without manually copying credentials.
Usage: poetry run python scripts/build_env_local.py
"""
import base64
import json
import os

try:
    import toml
except ImportError:
    print("Run: poetry install")
    raise SystemExit(1)

SECRETS_PATH = ".streamlit/secrets.toml"
OUT_PATH = ".env.local"


def main() -> None:
    if not os.path.isfile(SECRETS_PATH):
        print(f"{SECRETS_PATH} not found. Create it or copy .env.local.example to .env.local and fill in.")
        raise SystemExit(1)

    with open(SECRETS_PATH) as f:
        secrets = toml.load(f)

    lines = [
        "# Generated by scripts/build_env_local.py from .streamlit/secrets.toml",
        "# Do not commit .env.local",
        "",
    ]

    # Google Sheets: connections.gsheets is the service account dict.
    # Use base64 so .env.local has no quote/newline escaping issues.
    conn = secrets.get("connections", {})
    gsheets = conn.get("gsheets")
    if gsheets:
        json_str = json.dumps(gsheets, separators=(",", ":"))
        b64 = base64.standard_b64encode(json_str.encode("utf-8")).decode("ascii")
        lines.append(f"GOOGLE_SERVICE_ACCOUNT_JSON_B64={b64}")
    else:
        lines.append("# GOOGLE_SERVICE_ACCOUNT_JSON_B64=... (add from secrets [connections.gsheets])")

    # NRL auth
    nrl = conn.get("nrl", {})
    nrl_auth = nrl.get("auth", "")
    if nrl_auth:
        lines.append(f'NRL_AUTH="{nrl_auth}"')
    else:
        lines.append("# NRL_AUTH=... (add from secrets [connections.nrl] auth=...)")

    # Salt
    salt = secrets.get("salt", {})
    salt_val = salt.get("value", "")
    if salt_val:
        lines.append(f'PIN_SALT="{salt_val}"')
    else:
        lines.append("# PIN_SALT=... (optional)")

    lines.append("")

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines))

    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
